export const CANONICAL_URLS: Record<string, string> = {
  '/': 'https://highendinteriors.co.in/',
  '/about': 'https://highendinteriors.co.in/about',
  '/services': 'https://highendinteriors.co.in/services',
  '/portfolio': 'https://highendinteriors.co.in/portfolio',
  '/gallery': 'https://highendinteriors.co.in/gallery',
  '/contact': 'https://highendinteriors.co.in/contact',
  '/testimonials': 'https://highendinteriors.co.in/testimonials',
  '/reviews': 'https://highendinteriors.co.in/reviews',
  '/blog': 'https://highendinteriors.co.in/blog',
  '/faq': 'https://highendinteriors.co.in/faq',
  '/privacy-policy': 'https://highendinteriors.co.in/privacy-policy',
  '/terms': 'https://highendinteriors.co.in/terms',
  '/interior-designers-mumbai': 'https://highendinteriors.co.in/interior-designers-mumbai',
  '/best-interior-designers-mumbai': 'https://highendinteriors.co.in/best-interior-designers-mumbai',
  '/residential-interior-designers-mumbai': 'https://highendinteriors.co.in/residential-interior-designers-mumbai',
  '/commercial-interior-design-mumbai': 'https://highendinteriors.co.in/commercial-interior-design-mumbai',
  '/affordable-interior-designers-mumbai': 'https://highendinteriors.co.in/affordable-interior-designers-mumbai',
  '/luxury-interior-designers-mumbai': 'https://highendinteriors.co.in/luxury-interior-designers-mumbai',
  '/modular-kitchen-design-mumbai': 'https://highendinteriors.co.in/modular-kitchen-design-mumbai',
  '/2bhk-interior-design-mumbai': 'https://highendinteriors.co.in/2bhk-interior-design-mumbai',
  '/bedroom-interior-design-mumbai': 'https://highendinteriors.co.in/bedroom-interior-design-mumbai',
  '/living-room-interior-design-mumbai': 'https://highendinteriors.co.in/living-room-interior-design-mumbai',
  '/kitchen-interior-design-mumbai': 'https://highendinteriors.co.in/kitchen-interior-design-mumbai',
  '/office-interior-design-mumbai': 'https://highendinteriors.co.in/office-interior-design-mumbai',
  '/shop-interior-design-mumbai': 'https://highendinteriors.co.in/shop-interior-design-mumbai',
  '/false-ceiling-design-mumbai': 'https://highendinteriors.co.in/false-ceiling-design-mumbai',
  '/furniture-designers-mumbai': 'https://highendinteriors.co.in/furniture-designers-mumbai',
  '/home-interior-designer-mumbai': 'https://highendinteriors.co.in/home-interior-designer-mumbai',
  '/home-renovation-mumbai': 'https://highendinteriors.co.in/home-renovation-mumbai',
  '/turnkey-interior-solutions-mumbai': 'https://highendinteriors.co.in/turnkey-interior-solutions-mumbai',
  '/interior-designer-andheri': 'https://highendinteriors.co.in/interior-designer-andheri',
  '/interior-designer-bandra': 'https://highendinteriors.co.in/interior-designer-bandra',
  '/interior-designer-borivali': 'https://highendinteriors.co.in/interior-designer-borivali',
  '/interior-designer-thane': 'https://highendinteriors.co.in/interior-designer-thane',
  '/interior-designer-navi-mumbai': 'https://highendinteriors.co.in/interior-designer-navi-mumbai',
  '/interior-designer-vileparle-mumbai': 'https://highendinteriors.co.in/interior-designer-vileparle-mumbai',
  '/interior-decorators-mumbai': 'https://highendinteriors.co.in/interior-decorators-mumbai',
}

export function getCanonicalUrl(pathname: string): string {
  return CANONICAL_URLS[pathname] || `https://highendinteriors.co.in${pathname}`
}
